stages:
  load_req_data:
    cmd: python load_req_data.py
    deps:
    - load_req_data.py
    - raw_data/number.csv
    params:
    - filter_criteria.num
    outs:
    - output/req_data/output.csv

  analysis:
    cmd: python analysis.py
    deps:
    - analysis.py
    - output/req_data/output.csv
    params:
    - analysis.top_rows
    outs:
    - output/analysis/output.txt